@merge pipeline {
    agent none
    @merge stages {
        stage("Example Build") {
            steps {
                echo 'Example Build'
            }
        }

        stage("Example Deploy") {
            steps {
                echo 'Example Deploy'
            }
        }
    }
}
